
Vagrant.configure("2") do |config|
  config.vm.define "test2" do |test2|
    test2.vm.box = "ubuntu/focal64"
  end 

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/focal64"
    web.vm.network "private_network", ip: "192.168.56.10"
  end

  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/focal64"
    db.vm.network "private_network", ip: "192.168.56.11"
  end

end


